# Generated by Django 3.2.6 on 2021-08-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collab',
            old_name='todo',
            new_name='todos',
        ),
    ]
