# Generated by Django 3.0.7 on 2021-08-07 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_todo_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='contributors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Contributors'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
