# Generated by Django 3.2.6 on 2021-08-19 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_rename_todo_collab_todos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborators', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
                ('todo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.todo')),
            ],
        ),
        migrations.DeleteModel(
            name='collab',
        ),
    ]
