# Generated by Django 3.0.7 on 2021-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_collaboratoroftodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratoroftodo',
            name='collaborator_username',
            field=models.CharField(default='', max_length=500),
        ),
    ]
