# Generated by Django 3.2.6 on 2021-08-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210819_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboration',
            old_name='collaborators',
            new_name='user',
        ),
    ]
