# Generated by Django 3.0.7 on 2021-08-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='collab_name',
            field=models.CharField(max_length=255),
        ),
    ]
