# Generated by Django 3.0.7 on 2021-08-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210805_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='collaborating',
        ),
    ]
