# Generated by Django 3.2.6 on 2021-08-05 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_todo_collab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='collab',
        ),
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('collab', models.ManyToManyField(related_name='collab', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
