# Generated by Django 3.2.6 on 2021-08-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_collaborators_collaboration_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboration',
            old_name='user',
            new_name='collaborator',
        ),
    ]
