# Generated by Django 3.2.6 on 2021-08-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_collaboration_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.todo'),
        ),
    ]
