# Generated by Django 3.0.7 on 2021-08-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210807_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='collab_name',
            new_name='collab_username',
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='todo_id',
            field=models.IntegerField(),
        ),
    ]
