# Generated by Django 3.2.6 on 2021-08-07 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210807_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 18, 23, 28, 172887)),
        ),
    ]
