# Generated by Django 3.2.6 on 2021-08-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_collaboration_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboration',
            old_name='collaborator',
            new_name='collaborators',
        ),
    ]
