# Generated by Django 3.0.7 on 2021-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210807_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='collab_username',
            field=models.CharField(max_length=75),
        ),
    ]
