# Generated by Django 3.2.6 on 2021-08-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_todo_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='collab',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='api.todo'),
        ),
    ]
