# Generated by Django 3.2.6 on 2021-08-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210807_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
