# Generated by Django 3.2.6 on 2021-08-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_collab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
