# Generated by Django 3.2.6 on 2021-08-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_collab_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='api.todo'),
        ),
    ]
