# Generated by Django 3.2.6 on 2021-08-12 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_alter_collab_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='todo',
        ),
        migrations.AddField(
            model_name='collab',
            name='todo',
            field=models.ManyToManyField(null=True, to='api.Todo'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
