# Generated by Django 3.2.6 on 2021-08-12 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20210812_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='todo',
            field=models.ManyToManyField(to='api.Todo'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
