# Generated by Django 3.2.6 on 2021-08-11 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_alter_todo_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='collaborations',
            field=models.ManyToManyField(related_name='collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collab',
            name='todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.todo'),
        ),
    ]
