# Generated by Django 3.2.6 on 2021-08-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210811_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='collaborations',
        ),
    ]
