# Generated by Django 3.2.6 on 2021-08-12 10:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210812_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name=api.models.Todo),
        ),
    ]
