# Generated by Django 3.2.6 on 2021-08-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_collab_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='title',
        ),
    ]
