# Generated by Django 3.2.6 on 2021-08-16 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_auto_20210816_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='user',
        ),
        migrations.AddField(
            model_name='collab',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
